objects/Account/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is used to Know the Account is Active or Inactive.</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

objects/SQX_Team_Members__c/SQX_Team_Members__c.object-meta.xml
<CustomObject>
    <description>This Object is used in the CQ Interview round.</description>
    <label>Team Member</label>
    <nameField>
        <label>Team Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Team Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SQX_Team_Members__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>This field is used to store the Account Record.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Team Members</relationshipLabel>
    <relationshipName>Team_Members</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

objects/SQX_Team_Members__c/fields/Member_Type__c.field-meta.xml
<CustomField>
    <fullName>Member_Type__c</fullName>
    <description>This field is used to select the member type.</description>
    <label>Member Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>HR</fullName>
            </value>
            <value>
                <fullName>Admin</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

classes/Account_Handler.cls
public class Account_Handler {
    Public static void methodname(List<Account> acclist){
        Set<Id> accountIds = new Set<Id>();
        for(Account acc:acclist){
          accountIds.add(acc.Id);
        }
        List<SQX_Team_Members__c> team1 = [select id from SQX_Team_Members__c where Account__c In: accountIds AND Member_Type__c = 'Admin'];
        List<SQX_Team_Members__c> team2 = [select id from SQX_Team_Members__c where Account__c In: accountIds AND Member_Type__c = 'HR'];
        for(Account acc1: acclist){
            if((team1.size()==0 || team2.size()== 0) && acc1.Active__c==true){
                acc1.Active__C.adderror('Cannot activate account without HR And Admin team member record');
            }
        }
    }
}